### ISSUE TITLE
Is it possible to parse sitemap from file?

### ISSUE THREAD

**Issue by KarelWintersky** [VIPnytt/SitemapParser#19]
Is it possible to parse sitemap from local file?

**Comment by JanPetterMG** [comment]
Yes, that's possible.

Just add the contents of the file as the second parameter of `parse()`. The URL is still required to determine filetype, but won't be crawled.

Example:
````
$parser = new SitemapParser();
$parser->parse('https://example.com/sitemap.xml', 'INSERT_FILE_CONTENTS_HERE');
foreach ($parser->getURLs() as $url => $tags) {
    echo $url . '<br>';
}
````
