### ISSUE TITLE
allow proxy in guzzle

### ISSUE THREAD

**Issue by tacman** [VIPnytt/SitemapParser#26]
I'm trying to test this against a local website that uses the Symfony CLI to create a server.  There's a proxy that allows me to use custom domain names, e.g. https://my-demo.wip, to serve requests.

Unfortunately, I can't read the sitemap there, as I'd need to add the proxy servers, by adding them to the client.

https://www.zenrows.com/blog/guzzle-proxy#request-option

I've tried to set the proxies, but not having much luck:

```php
$proxies = [
            'http'  => 'http://127.0.0.1:7080/',
            'https' => 'http://127.0.0.1:7080/',
        ];
        $config = [
            'guzzle' =>
                [RequestOptions::PROXY => $proxies,
                      RequestOptions::VERIFY => false, # disable SSL certificate validation
    RequestOptions::TIMEOUT => 30, # timeout of 30 seconds
                ]
        ];

            $parser = new SitemapParser('MyCustomUserAgent', $config);
```

any suggestions?

It'd be great if that were documented.

**Comment by JanPetterMG** [comment]
I don't see any reason for this to not work. Have you tested that the proxies works as intended in GuzzleHttp natively?
There shouldn't be any difference, but you can create the GuzzleHttp instance manually and pass it thru to the SitemapParser instead if preferable, as documented in the Throttling example of the [README](https://github.com/VIPnytt/SitemapParser/tree/master?tab=readme-ov-file#throttling).
````
$config = [
    GuzzleHttp\RequestOptions::PROXY => [
        'http' => 'http://127.0.0.1:7080',
        'https' => 'http://127.0.0.1:7080',
    ],
    GuzzleHttp\RequestOptions::VERIFY => false,
    GuzzleHttp\RequestOptions::TIMEOUT => 30,
];
$client = new GuzzleHttp\Client($config);

$parser = new SitemapParser('MyCustomUserAgent');
$parser->setClient($client);
````

Here's the link to the _official_ GuzzleHttp Request Options documentation: https://docs.guzzlephp.org/en/stable/request-options.html
