### ISSUE TITLE
First example returns nothing

### ISSUE THREAD

**Issue by spekulatius** [VIPnytt/SitemapParser#9]
Hey @vipnytt,

I'm considering using your library in my [PHPScraper](https://github.com/spekulatius/phpscraper) and have been playing around with the examples. The first one didn't return anything - I guess it's due to the sitemap only containing other site maps. Maybe it would make sense to use a different one to reduce confusion?

Cheers,
Peter

**Comment by JanPetterMG** [comment]
Agree 👍
